[default]
debug = true
allowed_hosts = ["*"]
language_code = "en-us"
time_zone = "UTC"
use_i18n = true
use_tz = true

# Static and Media files
static_url = "static/"
media_url = "media/"

# Crispy Forms
crispy_allowed_template_packs = "bootstrap5"
crispy_template_pack = "bootstrap5"

# Authentication
login_redirect_url = "chat:chat_home"
logout_redirect_url = "login"
login_url = "login"

# Model configuration
[default.model_configs]
embeddings_model = "all-MiniLM-L6-v2"
chat_model = "deepseek"

[default.model_configs.all-MiniLM-L6-v2]
api_url = ""
version = "all-MiniLM-L6-v2"

[default.model_configs.openai]
api_url = "https://api.openai.com/v1/embeddings"
version = "text-embedding-3-small"

[default.model_configs.deepseek]
api_url = "https://openrouter.ai/api/v1"
version = "deepseek-chat-v3-0324:free"

[development]
debug = true

[production]
debug = false
