# Generated by Django 5.2 on 2025-05-26 17:19
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
    ]
